---
apiVersion: v2
name: kasm
description: |
  Kasm is a platform specializing in providing secure browser-based workspaces
  for a wide range of applications and industries. Its main goal is to provide
  isolated and secure environments that can be accessed via web browsers,
  ensuring that users can perform tasks without risking the security of their
  local systems.
type: application
version: 1.17.0
appVersion: "1.17.0"

home: https://kasmweb.com
icon: https://kasm-static-content.s3.amazonaws.com/icons/kasm-logo-small.png
keywords:
  - kasm
  - vdi
  - workspaces
  - virtual-desktop
  - browser-based
maintainers:
  - name: CFI2017
    url: https://github.com/cfi2017/kasm-helm

annotations:
  category: Virtual Desktop
  licenses: Apache-2.0
