{{- if .Values.services.proxy.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "kasm.fullname" . }}-proxy
  namespace: {{ include "kasm.namespace" . }}
  labels:
    {{- include "kasm.commonLabels" . | nindent 4 }}
    {{- include "kasm.componentLabels" "proxy" | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "kasm.selectorLabels" . | nindent 4 }}
    kasm.app/component: proxy
{{- end }}
