apiVersion: str()
name: str()
version: str()
description: str(required=False)
type: str(required=False)
keywords: list(str(), required=False)
home: str(required=False)
sources: list(str(), required=False)
dependencies: list(any(), required=False)
maintainers: list(any(), required=False)
icon: str(required=False)
appVersion: str(required=False)
deprecated: bool(required=False)
annotations: any(required=False)
