---
remote: origin
target-branch: main
chart-dirs:
  - charts
chart-repos: []
helm-extra-args: --timeout 600s
check-version-increment: true
validate-maintainers: false
chart-yaml-schema: .github/chart_schema.yaml
lint-conf: .github/lintconf.yaml
debug: false