{{- if .Values.services.api.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "kasm.fullname" . }}-password-injection
  namespace: {{ include "kasm.namespace" . }}
  labels:
    {{- include "kasm.commonLabels" . | nindent 4 }}
    {{- include "kasm.componentLabels" "password-injection" | nindent 4 }}
data:
  inject-passwords.sh: |
    #!/bin/sh
    set -e
    
    echo "Injecting passwords into configuration..."
    
    # Read passwords from secrets
    DB_PASSWORD=$(cat /secrets/database/password)
    REDIS_PASSWORD=$(cat /secrets/redis/password)
    
    # Create the password override config
    cat > /shared/password-config.yaml << EOF
    database:
      password: "${DB_PASSWORD}"
    redis:
      redis_password: "${REDIS_PASSWORD}"
    EOF
    
    echo "Password configuration injected successfully"
    cat /shared/password-config.yaml
{{- end }}