{{/*
Kasm Shared Secrets - Contains tokens and credentials shared across components
*/}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kasm.fullname" . }}-shared-secrets
  namespace: {{ include "kasm.namespace" . }}
  labels:
    {{- include "kasm.commonLabels" . | nindent 4 }}
    {{- include "kasm.componentLabels" "shared" | nindent 4 }}
type: Opaque
data:
  manager-token: {{ .Values.passwords.managerToken | default (uuidv4) | b64enc | quote }}
  service-token: {{ .Values.passwords.serviceToken | default (uuidv4) | b64enc | quote }}
  admin-password: {{ .Values.passwords.adminPassword | default (randAlphaNum 32) | b64enc | quote }}
  user-password: {{ .Values.passwords.userPassword | default (randAlphaNum 32) | b64enc | quote }}