{{- if .Values.services.api.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "kasm.fullname" . }}-api-config
  namespace: {{ include "kasm.namespace" . }}
  labels:
    {{- include "kasm.commonLabels" . | nindent 4 }}
    {{- include "kasm.componentLabels" "api-config" | nindent 4 }}
data:
  api.app.config.yaml: |
    # Kasm API Application Configuration
    database:
      name: {{ .Values.database.external.database | default "kasm" }}
      username: {{ .Values.database.external.username | default "kasmapp" }}
      password: changeme
      host: {{ include "kasm.databaseHost" . }}
      port: {{ include "kasm.databasePort" . }}
      type: postgres
      ssl: {{ eq (.Values.database.external.sslMode | default "prefer") "require" }}
      pool_size: {{ .Values.services.api.config.database.pool_size | default 10 }}
      max_overflow: {{ .Values.services.api.config.database.max_overflow | default 20 }}
    redis:
      host: {{ include "kasm.redisHost" . }}
      port: {{ include "kasm.redisPort" . }}
      redis_password: changeme
    logging:
      agent:
        formatters:
          pythonjsonlogger:
            (): pythonjsonlogger.jsonlogger.JsonFormatter
            fmt: '%(asctime) %(name) %(processName) %(filename)  %(funcName) %(levelname) %(lineno) %(module) %(threadName) %(message)'
            timestamp: true
          standard:
            format: '%(asctime)s [%(levelname)s] %(name)s: %(message)s'
        handlers:
          file_handler:
            backupCount: 20
            class: logging.handlers.RotatingFileHandler
            encoding: utf8
            filename: /opt/kasm/current/log/agent.log
            formatter: standard
            level: DEBUG
            maxBytes: 10485760
          file_handler_json:
            backupCount: 20
            class: logging.handlers.RotatingFileHandler
            encoding: utf8
            filename: /opt/kasm/current/log/agent_json.log
            formatter: pythonjsonlogger
            level: DEBUG
            maxBytes: 10485760
          stream:
            class: logging.StreamHandler
            formatter: standard
            level: INFO
          syslog:
            class: logging.handlers.SysLogHandler
            formatter: pythonjsonlogger
            level: DEBUG
        loggers:
          '':
            handlers:
            - stream
            - syslog
            - file_handler
            - file_handler_json
            level: DEBUG
            propagate: true
        version: 1
      kasm_share:
        formatters:
          pythonjsonlogger:
            (): pythonjsonlogger.jsonlogger.JsonFormatter
            fmt: '%(asctime) %(name) %(processName) %(filename)  %(funcName) %(levelname) %(lineno) %(module) %(threadName) %(message)'
            timestamp: true
          standard:
            format: '%(asctime)s [%(levelname)s] %(name)s: %(message)s'
        handlers:
          file_handler:
            backupCount: 20
            class: logging.handlers.RotatingFileHandler
            encoding: utf8
            filename: /opt/kasm/current/log/share.log
            formatter: standard
            level: DEBUG
            maxBytes: 10485760
          file_handler_json:
            backupCount: 20
            class: logging.handlers.RotatingFileHandler
            encoding: utf8
            filename: /opt/kasm/current/log/share_json.log
            formatter: pythonjsonlogger
            level: DEBUG
            maxBytes: 10485760
          stream:
            class: logging.StreamHandler
            formatter: standard
            level: DEBUG
          syslog:
            class: logging.handlers.SysLogHandler
            formatter: pythonjsonlogger
            level: DEBUG
        loggers:
          '':
            handlers:
            - stream
            - syslog
            - file_handler
            - file_handler_json
            level: DEBUG
            propagate: true
          tornado.application:
            level: DEBUG
          tornado.access:
            level: DEBUG
          tornado.general:
            level: DEBUG
        version: 1
      manager_api_server:
        filters:
          internal_log_filter:
            (): log.handlers.InternalLogFilter
          web_filter_log_filter:
            (): log.handlers.ExternalLogFilter
            application: 'kasm_squid_adapter'
        formatters:
          pythonjsonlogger:
            (): pythonjsonlogger.jsonlogger.JsonFormatter
            fmt: '%(asctime) %(name) %(processName) %(filename)  %(funcName) %(levelname) %(lineno) %(module) %(threadName) %(message)'
            timestamp: true
          standard:
            format: '%(asctime)s [%(levelname)s] %(name)s: %(message)s'
        handlers:
          file_handler:
            backupCount: 20
            class: logging.handlers.RotatingFileHandler
            encoding: utf8
            filename: /opt/kasm/current/log/manager_api_server.log
            formatter: standard
            level: DEBUG
            maxBytes: 10485760
            filters: [ internal_log_filter ]
          file_handler_json:
            backupCount: 20
            class: logging.handlers.RotatingFileHandler
            encoding: utf8
            filename: /opt/kasm/current/log/manager_api_server_json.log
            formatter: pythonjsonlogger
            level: DEBUG
            maxBytes: 10485760
            filters: [ internal_log_filter ]
          web_filter_file_handler:
            backupCount: 20
            class: logging.handlers.RotatingFileHandler
            encoding: utf8
            filename: /opt/kasm/current/log/web_filter_access_json.log
            level: DEBUG
            maxBytes: 10485760
            filters: [ web_filter_log_filter ]
          stream:
            class: logging.StreamHandler
            formatter: standard
            level: INFO
            filters: [ internal_log_filter ]
          syslog:
            class: logging.handlers.SysLogHandler
            formatter: pythonjsonlogger
            level: DEBUG
            filters: [ internal_log_filter ]
        loggers:
          '':
            handlers:
            - stream
            - syslog
            - file_handler
            - file_handler_json
            - web_filter_file_handler
            level: DEBUG
            propagate: true
          __main__.handler:
            level: DEBUG
          googleapiclient.discovery_cache:
            level: ERROR
          provider_manager:
            level: DEBUG
          provider:
            level: DEBUG
          tornado:
            level: INFO
          sqlalchemy.pool:
            level: WARNING
          sqlalchemy.pool.status:
            level: WARNING
          sqlalchemy.engine:
            level: WARNING
          sqlalchemy.dialects:
            level: WARNING
          sqlalchemy.orm:
            level: WARNING
          botocore:
            level: WARNING
          azure:
            level: WARNING
          database_models:
            level: INFO
          keystoneauth.session:
            level: WARNING
          novaclient.v2.client:
            level: WARNING
        version: 1
      api_server:
        filters:
          request_context_filter:
            (): utils.RequestContextFilter
        formatters:
          pythonjsonlogger:
            (): pythonjsonlogger.jsonlogger.JsonFormatter
            fmt: '%(asctime) %(name) %(processName) %(filename)  %(funcName) %(levelname) %(lineno) %(module) %(threadName) %(message)'
            timestamp: true
          standard:
            format: '%(asctime)s [%(levelname)s] %(name)s: %(message)s'
        handlers:
          file_handler:
            backupCount: 20
            class: logging.handlers.RotatingFileHandler
            encoding: utf8
            filename: /opt/kasm/current/log/api_server.log
            formatter: standard
            level: DEBUG
            maxBytes: 10485760
          file_handler_json:
            backupCount: 20
            class: logging.handlers.RotatingFileHandler
            encoding: utf8
            filename: /opt/kasm/current/log/api_server_json.log
            formatter: pythonjsonlogger
            level: DEBUG
            maxBytes: 10485760
            filters: [request_context_filter]
          subscription_file_handler:
            backupCount: 20
            class: logging.handlers.RotatingFileHandler
            encoding: utf8
            filename: /opt/kasm/current/log/subscription_api_server.log
            formatter: standard
            level: DEBUG
            maxBytes: 10485760
          admin_file_handler:
            backupCount: 20
            class: logging.handlers.RotatingFileHandler
            encoding: utf8
            filename: /opt/kasm/current/log/admin_api_server.log
            formatter: standard
            level: DEBUG
            maxBytes: 10485760
          client_file_handler:
            backupCount: 20
            class: logging.handlers.RotatingFileHandler
            encoding: utf8
            filename: /opt/kasm/current/log/client_api_server.log
            formatter: standard
            level: DEBUG
            maxBytes: 10485760
          stream:
            class: logging.StreamHandler
            formatter: standard
            level: DEBUG
          syslog:
            class: logging.handlers.SysLogHandler
            formatter: pythonjsonlogger
            level: DEBUG
        loggers:
          '':
            handlers:
            - stream
            - syslog
            - file_handler
            - file_handler_json
            level: DEBUG
            propagate: true
          client_api_server:
            handlers:
              - client_file_handler
          admin_api_server:
            handlers:
              - admin_file_handler
          subscription_api_server:
            handlers:
              - subscription_file_handler
          cherrypy.error:
            level: INFO
          cherrypy.access:
            level: INFO
          sqlalchemy.pool:
            level: WARNING
          sqlalchemy.pool.status:
            level: WARNING
          sqlalchemy.engine:
            level: WARNING
          sqlalchemy.dialects:
            level: WARNING
          sqlalchemy.orm:
            level: WARNING
          requests_oauthlib:
            level: INFO
          database_models:
            level: INFO
          googleapiclient.discovery_cache:
            level: ERROR
          keystoneauth.session:
            level: WARNING
          novaclient.v2.client:
            level: WARNING
          botocore:
            level: WARNING
          azure:
            level: WARNING
        version: 1
    manager:
      manager_id: {{ .Values.services.api.config.manager.manager_id | default "null" }}
      update_timer: {{ .Values.services.api.config.manager.update_timer | default 86400 }}
    server:
      server_id: {{ .Values.services.api.config.server.server_id | default "null" }}
      server_hostname: {{ .Values.services.api.config.server.server_hostname | default "null" }}
      zone_name: {{ .Values.kasm.zoneName | default "default" }}
      sanitize_errors: {{ .Values.services.api.config.server.sanitize_errors | default true }}
      internal_schema: {{ .Values.services.api.config.server.internal_schema | default "https" }}
      kubernetes: {{ .Values.services.api.config.server.kubernetes | default false }}
    share:
      share_id: {{ .Values.services.api.config.share.share_id | default "null" }}
      
    {{- with .Values.services.api.config.additional }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
{{- end }}