---
name: Chart Validation

'on':
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  lint-and-validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v4
        with:
          version: v3.12.1

      - name: Add Helm repositories (if needed)
        run: |
          helm repo add bitnami https://charts.bitnami.com/bitnami
          helm repo update

      - name: Lint Helm chart
        run: |
          helm lint charts/kasm

      - name: Validate chart templates render without error
        run: |
          helm template test-release charts/kasm --debug --dry-run > /dev/null
          echo "✅ Chart templates render successfully"

  helm-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run helm-docs
        uses: docker://jnorwood/helm-docs:latest
        with:
          args: --chart-search-root=charts

      - name: Check for changes
        run: |
          if git diff --exit-code; then
            echo "Documentation is up to date"
          else
            echo "Documentation is out of date."
            echo "Please run helm-docs and commit the changes."
            exit 1
          fi
